---
- name: obtener datos
  hosts: localhost
  gather_facts: yes
  tasks:

    - name: connecting to jira
      uri:
        url: https://invk2.atlassian.net/rest/api/3/issue/10000/attachments
        user: jaromero@redhat.com
        password: ATATT3xFfGF0i6wcMbSPkTGWMbvnP6G6oZgvggji9xzgypOAdY0IUr3oibNPfodwAvOAamj9nJMS--MyoM8L1PINKU93TQwKH_4pqX3EeTyoRRYTmgch2ejNfzoJOpWmPeEY9ZM5FVeRWugiHPV9p1TMkTUjlBM8-Y3jM9Z791w3c02_-0aTQs4=FA3E0386
        status_code: [200, 201]
        method: POST
        body_format: json
      validate_certs: no
      register: Status