---
- name: Conexion local
  hosts: localhost
  gather_facts: false
  tasks:

    - name: connecting to jira
      uri:
      url: https://invk2.atlassian.net/
      user: 'jaromero@redhat.com'
      password: 'Pichilemu2012#'
      method: GET
      return_content: yes
      status_code: 200
      register: Status

    - debug:
        var: Status.stdout_lines