---
- name: obtener datos
  hosts: localhost
  gather_facts: yes
  tasks:

    # - name: Download file with custom HTTP headers
    #   ansible.builtin.uri:
    #     url: "https://invk2.atlassian.net/rest/api/3/issue/10000/attachments"
    #     method: POST 
    #     headers:
    #       Authorization: 'Basic a3phdmFsYUByZWRoYXQuY29tOkFUQVRUM3hGZkdGMHoxVU5pQWd2a0t1Z1NCbGRBNnlXS3ZMSU52cVF6MEdwQ1NSWU9aeGNaUXFDVUhYeHFCWlhzamsxYnJzTl9udThhSnl3WFI1SFZMckZJNXlENVpnaG5EMmtoMkpYQ1FsckJDRUpNLU9UN1pkMFRyeEdLREczRV93LWx0NVMtei1WNjVGZDhpRWQxbGZETnFLbkl5WUZRbF9oUWdzV0RYRDdCd1BtYUt4eEtOYz01NDI3QTBDNw=='


    # - uri: 
    #     url: https://invk2.atlassian.net/rest/api/3/issue/10000/attachments
    #     user: 'jaromero@redhat.com'
    #     password: 'ATATT3xFfGF0i6wcMbSPkTGWMbvnP6G6oZgvggji9xzgypOAdY0IUr3oibNPfodwAvOAamj9nJMS--MyoM8L1PINKU93TQwKH_4pqX3EeTyoRRYTmgch2ejNfzoJOpWmPeEY9ZM5FVeRWugiHPV9p1TMkTUjlBM8-Y3jM9Z791w3c02_-0aTQs4=FA3E0386'
    #     body: "{{ lookup('file','jiradownload.yml') }}" 
    #     method: POST 
    #     force_basic_auth: yes

    - name: listado de volumnes log
      ansible.builtin.shell: "df -h >> texttest.txt"
      register: partition_log_1

    - name: Create Jira Project
      uri:        
        url: 'https://invk2.atlassian.net/rest/api/3/issue/10000/attachments'
        method: GET
        status_code: [200, 201]
        headers:
          Authorization: 'Basic a3phdmFsYUByZWRoYXQuY29tOkFUQVRUM3hGZkdGMHoxVU5pQWd2a0t1Z1NCbGRBNnlXS3ZMSU52cVF6MEdwQ1NSWU9aeGNaUXFDVUhYeHFCWlhzamsxYnJzTl9udThhSnl3WFI1SFZMckZJNXlENVpnaG5EMmtoMkpYQ1FsckJDRUpNLU9UN1pkMFRyeEdLREczRV93LWx0NVMtei1WNjVGZDhpRWQxbGZETnFLbkl5WUZRbF9oUWdzV0RYRDdCd1BtYUt4eEtOYz01NDI3QTBDNw=='
